package app;
// Generated Mar 2, 2017 11:04:18 PM by Hibernate Tools 4.3.1



/**
 * Chitiethoadon generated by hbm2java
 */
public class Chitiethoadon  implements java.io.Serializable {


     private String maSp;
     private Hoadon hoadon;
     private Sanpham sanpham;
     private String soLuongMua;
     private String email;

    public Chitiethoadon() {
    }

    public Chitiethoadon(Hoadon hoadon, Sanpham sanpham, String soLuongMua, String email) {
       this.hoadon = hoadon;
       this.sanpham = sanpham;
       this.soLuongMua = soLuongMua;
       this.email = email;
    }
   
    public String getMaSp() {
        return this.maSp;
    }
    
    public void setMaSp(String maSp) {
        this.maSp = maSp;
    }
    public Hoadon getHoadon() {
        return this.hoadon;
    }
    
    public void setHoadon(Hoadon hoadon) {
        this.hoadon = hoadon;
    }
    public Sanpham getSanpham() {
        return this.sanpham;
    }
    
    public void setSanpham(Sanpham sanpham) {
        this.sanpham = sanpham;
    }
    public String getSoLuongMua() {
        return this.soLuongMua;
    }
    
    public void setSoLuongMua(String soLuongMua) {
        this.soLuongMua = soLuongMua;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


