package app;
// Generated Mar 2, 2017 11:04:18 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Hoadon generated by hbm2java
 */
public class Hoadon  implements java.io.Serializable {


     private String maHd;
     private Khachhang khachhang;
     private Date ngayLap;
     private Set<Chitiethoadon> chitiethoadons = new HashSet<Chitiethoadon>(0);

    public Hoadon() {
    }

	
    public Hoadon(String maHd, Khachhang khachhang, Date ngayLap) {
        this.maHd = maHd;
        this.khachhang = khachhang;
        this.ngayLap = ngayLap;
    }
    public Hoadon(String maHd, Khachhang khachhang, Date ngayLap, Set<Chitiethoadon> chitiethoadons) {
       this.maHd = maHd;
       this.khachhang = khachhang;
       this.ngayLap = ngayLap;
       this.chitiethoadons = chitiethoadons;
    }
   
    public String getMaHd() {
        return this.maHd;
    }
    
    public void setMaHd(String maHd) {
        this.maHd = maHd;
    }
    public Khachhang getKhachhang() {
        return this.khachhang;
    }
    
    public void setKhachhang(Khachhang khachhang) {
        this.khachhang = khachhang;
    }
    public Date getNgayLap() {
        return this.ngayLap;
    }
    
    public void setNgayLap(Date ngayLap) {
        this.ngayLap = ngayLap;
    }
    public Set<Chitiethoadon> getChitiethoadons() {
        return this.chitiethoadons;
    }
    
    public void setChitiethoadons(Set<Chitiethoadon> chitiethoadons) {
        this.chitiethoadons = chitiethoadons;
    }




}


